
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "FROM IDENTIFIER SELECT SEMICOLONplsql_block : select_statementselect_statement : SELECT identifier_list FROM IDENTIFIER SEMICOLONidentifier_list : IDENTIFIER\n                      | identifier_list ',' IDENTIFIER"
    
_lr_action_items = {'SELECT':([0,],[3,]),'$end':([1,2,10,],[0,-1,-2,]),'IDENTIFIER':([3,6,7,],[5,8,9,]),'FROM':([4,5,9,],[6,-3,-4,]),',':([4,5,9,],[7,-3,-4,]),'SEMICOLON':([8,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'plsql_block':([0,],[1,]),'select_statement':([0,],[2,]),'identifier_list':([3,],[4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> plsql_block","S'",1,None,None,None),
  ('plsql_block -> select_statement','plsql_block',1,'p_plsql_block','analizarSQL1.py',12),
  ('select_statement -> SELECT identifier_list FROM IDENTIFIER SEMICOLON','select_statement',5,'p_select_statement','analizarSQL1.py',16),
  ('identifier_list -> IDENTIFIER','identifier_list',1,'p_identifier_list','analizarSQL1.py',20),
  ('identifier_list -> identifier_list , IDENTIFIER','identifier_list',3,'p_identifier_list','analizarSQL1.py',21),
]
