-- PL/SQL BLOCK
BEGIN

  VNCONTADOR := 0;

  AOCRESPRO := '0';
  AOCMENERR := NULL;

 SELECT COUNT(*)
  INTO VNCONTADOR
  FROM ESQUEMA.TABLA0 WHERE CODOPEREC = AINCODOPEREC
    AND SECREC    = AINSECREC;
    --AND CODFUN    = TO_CHAR(AICCODFUN);

  SELECT COUNT(*)
  INTO VNCONTADOR
  FROM TABLA1
  WHERE CODOPEREC = AINCODOPEREC
    AND SECREC    = AINSECREC;
    --AND CODFUN    = TO_CHAR(AICCODFUN);

  IF VNCONTADOR = 0 THEN
    AOCMENERR := 'LA OPERACION ' || AINSECREC || ' NO ESTA REGISTRADA EN EL SISTEMA' ;
      RETURN;
  END IF;

  SELECT COUNT(*)
  INTO VNCONTADOR
  FROM TABLA2, ESQUEMA.TABLA3
  WHERE CODOPEREC = AINCODOPEREC
    AND SECREC    = AINSECREC
    AND ESTOPE    = 'ANU';

FOR IND IN (SELECT * FROM TABLA4 )
LOOP
END LOOP

SELECT * INTO V FROM TABLA5 AS T5;


  IF VNCONTADOR = 1 THEN
    AOCMENERR := 'LA OPERACION ' ||

SELECT * INTO V FROM TABLA6 JOINT TABLA7;

SELECT (SELECT C1 FROM TABLA8) , C2 INTO V FROM TABLA9;

SELECT * INTO V FROM TABLA10 ;

SELECT * INTO V FROM TABLA11;
SELECT C1 FROM TABLA12;

